#!/bin/bash

set -e
set -o pipefail

IN="${1}"

if [ ! -e "${IN}" ]; then
  echo "file not found!" >&2
  exit 1
fi

if ! head -n1 "${IN}" | grep -q "zrc-file 1\.0"; then
  echo "invalid file format!" >&2
  exit 1
fi

OUTFILE="$(grep "@output:" "${IN}" | cut -d : -f 2)"

if [ -z "${OUTFILE}" ]; then
  echo "no @output definition!" >&2
  exit 1
fi

echo "// autogenerated" > "${OUTFILE}"

tail -n "+2" "${IN}" | while IFS= read -r LINE; do
  NAME="$(echo "${LINE}" | cut -d ':' -f 1)"
  SRC="$(echo "${LINE}" | cut -d ':' -f 2)"

  if ! echo "${NAME}" | grep -q "^@"; then
    echo "pub const ${NAME} = @embedFile(\"../${SRC}\");" >> "${OUTFILE}"
  fi
done 