name: Autogenerate Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#          submodules: "recursive" 
        
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
        
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip     # install pip
          python3 -m pip install mkdocs            # install mkdocs 
          python3 -m pip install mkdocs-material   # install material theme
        
      - name: Build site
        working-directory: docs
        run: mkdocs build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "docs/site/"
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME }}
            TARGET: "/home/dunstblick-ci/website"


      ##- name: Deploy files to dunstwolke.org
      ##  uses: appleboy/scp-action@master
      ##  env:
      ##    HOST: ${{ secrets.HOST }}
      ##    USERNAME: ${{ secrets.USERNAME }}
      ##    PORT: ${{ secrets.PORT }}
      ##    KEY: ${{ secrets.KEY }}
      ##  with:
      ##    source: "./docs/site/*"
      ##    target: "/home/dunstblick-ci/website"
      ##    strip_components: 2
